# The backtrace for rust is almost as large as the entire binary.
# = Huge reduction in binary size by removing all that.
[profile.release]
panic = "immediate-abort"

[unstable]
panic-immediate-abort = true
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size"]
